#define CAN_ID_MESSAGE5VALUETABLESIGS 4
#define CAN_ID_MESSAGE4ODDSIZES 3
#define CAN_ID_MESSAGE3 2
#define CAN_ID_MESSAGE2SMALLER 1
#define CAN_ID_MESSAGE1 0

#define CAN_ENUM_VALUETABLESIGNAL1_INVALIDGARBAGE 2
#define CAN_ENUM_VALUETABLESIGNAL1_FINISHED 1
#define CAN_ENUM_VALUETABLESIGNAL1_STARTED 0

#define CAN_ENUM_SIMPLEVALUETABLE_INVALIDGARBAGE 2
#define CAN_ENUM_SIMPLEVALUETABLE_FINISHED 1
#define CAN_ENUM_SIMPLEVALUETABLE_STARTED 0
