#define CAN_WRAP_ID_PPTMISFIRECOUNT 6
#define CAN_WRAP_ID_PPTTIMINGSTATUS 5
#define CAN_WRAP_ID_FIRINGSTATUS 4
#define CAN_WRAP_ID_VOLTAGECURRENTINFO 3
#define CAN_WRAP_ID_BATTERYSTATUS 2
#define CAN_WRAP_ID_POWERSTATUS 1
#define CAN_WRAP_ID_MCUSTATUS 0
