% Auto-generated by Data Acquisition Toolbox Analog Input Recorder on 28-Apr-2018 16:18:27

%% Create Data Acquisition Session
% Create a session for the specified vendor.
s = daq.createSession('ni');

%% Set Session Properties
% Set properties that are not using default values.
s.Rate = 12500;

%% Add Channels to Session
% Add channels and set channel properties, if any.
channel1 = addAnalogInputChannel(s,'Dev1','ai0','Voltage');
channel1.TerminalConfig = 'SingleEnded';

channel2 = addAnalogInputChannel(s,'Dev1','ai1','Voltage');
channel2.TerminalConfig = 'SingleEnded';

channel3 = addAnalogInputChannel(s,'Dev1','ai3','Voltage');
channel3.TerminalConfig = 'SingleEnded';

channel4 = addAnalogInputChannel(s,'Dev1','ai2','Voltage');
channel4.TerminalConfig = 'SingleEnded';

addAnalogInputChannel(s,'Dev1','ai4','Voltage');

addAnalogInputChannel(s,'Dev1','ai5','Voltage');

addAnalogInputChannel(s,'Dev1','ai6','Voltage');

addAnalogInputChannel(s,'Dev1','ai7','Voltage');

%% Acquire Data
% Start the session in foreground.
[data, timestamps, starttime] = startForeground(s);

%% Log Data
% Convert the acquired data and timestamps to a timetable in a workspace variable.
ai0 = data(:,1);
ai1 = data(:,2);
ai3 = data(:,3);
ai2 = data(:,4);
ai4 = data(:,5);
ai5 = data(:,6);
ai6 = data(:,7);
ai7 = data(:,8);
DAQ_input = timetable(seconds(timestamps),ai0,ai1,ai3,ai2,ai4,ai5,ai6,ai7);

%% Plot Data
% Plot the acquired data on labeled axes.
plot(DAQ_input.Time, DAQ_input.Variables)
xlabel('Time')
ylabel('Amplitude (V)')
legend(DAQ_input.Properties.VariableNames)

%% Clean Up
% Clear the session and channels, if any.
clear s channel1 channel2 channel3 channel4

